# Generated by Django 5.0.6 on 2024-05-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingdate',
            new_name='booking_date',
        ),
    ]
